name: flutter_application_22
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0  # For downloading XML & ZIP
  archive: ^4.0.3  # For extracting ZIP
  process_run: ^0.12.2  # For executing root commands
  xml: ^6.5.0  # For parsing XML
  path_provider: ^2.1.5  # For getting file storage paths
  open_file: ^3.2.1
  cupertino_icons: ^1.0.8
  permission_handler: ^11.4.0
  flutter_launcher_icons: ^0.13.1  # Added for app icon setup
  
 
  
  
  
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    - assets/icon.jpg  # Make sure this file exists
    - assets/  # Ensure this directory exists

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"  # Ensure this file exists
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.jpg"
